import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <footer className="bg-gray-800 text-white text-center py-4 w-full fixed bottom-0">
          <p className="text-sm">Made by Ayman :{')'}</p>
        </footer>
      </body>


    </html>
  );
}


// components/Navbar.js
const Navbar = () => {
  return (
    <nav className =" h-16 flex items-center justify-items-start">
      <Link href="/"><div className="text-2xl ml-36 font-bold "><span className="text-red-500">R</span><span className="text-yellow-400">P</span><span className="text-green-500">S</span></div></Link>
    </nav>
  );
};


